CREATE DATABASE STORES;
USE STORES;
DROP DATABASE STORES;
CREATE TABLE EMPLOYEES (
EMP_ID INT,
EMP_NAME VARCHAR(50),
EMP_CITY VARCHAR(50),
EMP_SALARY DECIMAL(7,2),
JOIN_DATE DATE
);
SELECT * FROM EMPLOYEES;
RENAME TABLE EMPLOYEES TO CUSTOMER;
SELECT * FROM CUSTOMER;
RENAME TABLE CUSTOMER TO EMPLOYEES;
DROP TABLE EMPLOYEES;
ALTER TABLE EMPLOYEES
ADD EMAIL VARCHAR(10);
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES
ADD EMP_PH_NUM VARCHAR(10);
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES
MODIFY COLUMN EMP_CITY VARCHAR(50)
AFTER JOIN_DATE;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES
DROP COLUMN EMP_PH_NUM;
SELECT * FROM EMPLOYEES;


